version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php8-alpine
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - php-mysql-net
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - php-mysql-net

volumes:
  mysql_data:

networks:
  php-mysql-net: